#define MK_CTRL   0x01
#define MK_SHIFT  0x02
#define MK_ALT    0x04
#define MK_GUI    0x08
#define MK_LCTRL  0x01
#define MK_LSHIFT 0x02
#define MK_LALT   0x04
#define MK_LGUI   0x08
#define MK_RCTRL  0x10
#define MK_RSHIFT 0x20
#define MK_RALT   0x40
#define MK_RGUI   0x80

#define KS_POWER_DOWN   0x81
#define KS_SLEEP        0x82
#define KS_WAKE_UP      0x83

#define KM_PLAY          0xB0
#define KM_PAUSE         0xB1
#define KM_RECORD        0xB2
#define KM_FAST_FORWARD  0xB3
#define KM_REWIND        0xB4
#define KM_NEXT          0xB5
#define KM_PREV          0xB6
#define KM_STOP          0xB7
#define KM_EJECT         0xB8
#define KM_RAND_PLAY     0xB0
#define KM_PLAY_PAUSE    0xCD
#define KM_PLAY_SKIP     0xCE
#define KM_MUTE          0xE2
#define KM_VOL_INC       0xE9
#define KM_VOL_DEC       0xEA

#define K_A                   4 
#define K_B                   5 
#define K_C                   6 
#define K_D                   7 
#define K_E                   8 
#define K_F                   9 
#define K_G                   10 
#define K_H                   11 
#define K_I                   12 
#define K_J                   13 
#define K_K                   14 
#define K_L                   15 
#define K_M                   16 
#define K_N                   17 
#define K_O                   18 
#define K_P                   19 
#define K_Q                   20 
#define K_R                   21 
#define K_S                   22 
#define K_T                   23 
#define K_U                   24 
#define K_V                   25 
#define K_W                   26 
#define K_X                   27 
#define K_Y                   28 
#define K_Z                   29 
#define K_1                   30 
#define K_2                   31 
#define K_3                   32 
#define K_4                   33 
#define K_5                   34 
#define K_6                   35 
#define K_7                   36 
#define K_8                   37 
#define K_9                   38 
#define K_0                   39 
#define K_RET                 40 
#define K_ESC                 41 
#define K_BSPC                42 
#define K_TAB                 43 
#define K_SPC                 44 
#define K_MINUS               45 
#define K_EQUAL               46 
#define K_LBRACE              47 
#define K_RBRACE              48 
#define K_BSLASH              49 
#define K_NON_US_NUM          50 
#define K_SCOL                51 
#define K_QUOTE               52 
#define K_TILDE               53 
#define K_COMMA               54 
#define K_DOT                 55 
#define K_SLASH               56 
#define K_CPSLK               57 
#define K_F1                  58 
#define K_F2                  59 
#define K_F3                  60 
#define K_F4                  61 
#define K_F5                  62 
#define K_F6                  63 
#define K_F7                  64 
#define K_F8                  65 
#define K_F9                  66 
#define K_F10                 67 
#define K_F11                 68 
#define K_F12                 69 
#define K_PRSCR               70 
#define K_SCRLLK              71 
#define K_PAUSE               72 
#define K_INSERT              73 
#define K_HOME                74 
#define K_PGUP                75 
#define K_DEL                 76 
#define K_END                 77 
#define K_PGDN                78 
#define K_RIGHT               79 
#define K_LEFT                80 
#define K_DOWN                81 
#define K_UP                  82 
#define K_NUM_LOCK            83 
#define K_NON_US_BS           100 
#define K_MENU                101 
#define K_F13                 104 
#define K_F14                 105 
#define K_F15                 106 
#define K_F16                 107 
#define K_F17                 108 
#define K_F18                 109 
#define K_F19                 110 
#define K_F20                 111 
#define K_F21                 112 
#define K_F22                 113 
#define K_F23                 114 
#define K_F24                 115

#define KP_SLASH            84 
#define KP_ASTERIX          85 
#define KP_MINUS            86 
#define KP_PLUS             87 
#define KP_ENTER            88 
#define KP_1                89 
#define KP_2                90 
#define KP_3                91 
#define KP_4                92 
#define KP_5                93 
#define KP_6                94 
#define KP_7                95 
#define KP_8                96 
#define KP_9                97 
#define KP_0                98 
#define KP_DOT              99 

#define K_SYSRQ 154
